name: Test custom url
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build_debian_bullseye:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        base_image: https://raspi.debian.net/tested/20220121_raspi_1_bullseye.img.xz
        commands: |
          cat /etc/os-release
          uname -a

  build_ubuntu_22_04:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        base_image: https://cdimage.ubuntu.com/releases/22.04.2/release/ubuntu-22.04.2-preinstalled-server-arm64+raspi.img.xz
        commands: |
          cat /etc/os-release
          uname -a

  build_nvidia_orin:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Increase free space
      # Remove Android and dotnet
      run: |
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        df -h
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        base_image: https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v3.1/sd_card_b49/jp511-orin-nano-sd-card-image.zip
        rootpartition: 1
        commands: |
          cat /etc/os-release
          uname -a
